#Complete Your Makefile here

grade:
	perl grader.pl 4 2 12

test0: pa11
	@$(VALGRIND) --log-file=outputs/memoutput0 ./pa11 inputs/input0 outputs/output0
	diff -w outputs/output0 expected/expected0

test1: pa11
	@$(VALGRIND) --log-file=outputs/memoutput1 ./pa11 inputs/input1 outputs/output1
	diff -w outputs/output1 expected/expected1

test2: pa11
	@$(VALGRIND) --log-file=outputs/memoutput2 ./pa11 inputs/input2 outputs/output2
	diff -w outputs/output2 expected/expected2

test3: pa11
	@$(VALGRIND) --log-file=outputs/memoutput3 ./pa11 inputs/input3 outputs/output3
	diff -w outputs/output3 expected/expected3

test4: pa11
	@$(VALGRIND) --log-file=outputs/memoutput4 ./pa11 inputs/input4 outputs/output4
	diff -w outputs/output4 expected/expected4

test5: pa11
	@$(VALGRIND) --log-file=outputs/memoutput5 ./pa11 inputs/input5 outputs/output5
	diff -w outputs/output5 expected/expected5

test6: pa11
	@$(VALGRIND) --log-file=outputs/memoutput6 ./pa11 inputs/input6 outputs/output6
	diff -w outputs/output6 expected/expected6

test7: pa11
	@$(VALGRIND) --log-file=outputs/memoutput7 ./pa11 inputs/input7 outputs/output7
	diff -w outputs/output7 expected/expected7

test8: pa11
	@$(VALGRIND) --log-file=outputs/memoutput8 ./pa11 inputs/input8 outputs/output8
	diff -w outputs/output8 expected/expected8

test9: pa11
	@$(VALGRIND) --log-file=outputs/memoutput9 ./pa11 inputs/input9 outputs/output9
	diff -w outputs/output9 expected/expected9

test10: pa11
	@$(VALGRIND) --log-file=outputs/memoutput10 ./pa11 inputs/input10 outputs/output10
	diff -w outputs/output10 expected/expected10

test11: pa11
	@$(VALGRIND) --log-file=outputs/memoutput11 ./pa11 inputs/input11 outputs/output11
	diff -w outputs/output11 expected/expected11

extra: pa11
	@$(VALGRIND) --log-file=outputs/memoutput12 ./pa11 inputs/extra12 outputs/output12
	diff -w outputs/output12 expected/expected12
	@$(VALGRIND) --log-file=outputs/memoutput13 ./pa11 inputs/extra13 outputs/output13
	diff -w outputs/output13 expected/expected13
	@$(VALGRIND) --log-file=outputs/memoutput14 ./pa11 inputs/extra14 outputs/output14
	diff -w outputs/output14 expected/expected14
	@$(VALGRIND) --log-file=outputs/memoutput15 ./pa11 inputs/extra15 outputs/output15
	diff -w outputs/output15 expected/expected15
	@$(VALGRIND) --log-file=outputs/memoutput16 ./pa11 inputs/extra16 outputs/output16
	diff -w outputs/output16 expected/expected16
	@$(VALGRIND) --log-file=outputs/memoutput17 ./pa11 inputs/extra17 outputs/output17
	diff -w outputs/output17 expected/expected17
	@$(VALGRIND) --log-file=outputs/memoutput18 ./pa11 inputs/extra18 outputs/output18
	diff -w outputs/output18 expected/expected18
	@$(VALGRIND) --log-file=outputs/memoutput19 ./pa11 inputs/extra19 outputs/output19
	diff -w outputs/output19 expected/expected19
	@$(VALGRIND) --log-file=outputs/memoutput20 ./pa11 inputs/extra20 outputs/output20
	diff -w outputs/output20 expected/expected20
	@$(VALGRIND) --log-file=outputs/memoutput21 ./pa11 inputs/extra21 outputs/output21
	diff -w outputs/output21 expected/expected21
	@$(VALGRIND) --log-file=outputs/memoutput22 ./pa11 inputs/extra22 outputs/output22
	diff -w outputs/output22 expected/expected22
	@$(VALGRIND) --log-file=outputs/memoutput23 ./pa11 inputs/extra23 outputs/output23
	diff -w outputs/output23 expected/expected23
	@$(VALGRIND) --log-file=outputs/memoutput24 ./pa11 inputs/extra24 outputs/output24
	diff -w outputs/output24 expected/expected24
	@$(VALGRIND) --log-file=outputs/memoutput25 ./pa11 inputs/extra25 outputs/output25
	diff -w outputs/output25 expected/expected25
	@$(VALGRIND) --log-file=outputs/memoutput26 ./pa11 inputs/extra26 outputs/output26
	diff -w outputs/output26 expected/expected26
	@$(VALGRIND) --log-file=outputs/memoutput27 ./pa11 inputs/extra27 outputs/output27
	diff -w outputs/output27 expected/expected27
	@$(VALGRIND) --log-file=outputs/memoutput28 ./pa11 inputs/extra28 outputs/output28
	diff -w outputs/output28 expected/expected28
	@$(VALGRIND) --log-file=outputs/memoutput29 ./pa11 inputs/extra29 outputs/output29
	diff -w outputs/output29 expected/expected29
	@$(VALGRIND) --log-file=outputs/memoutput30 ./pa11 inputs/extra30 outputs/output30
	diff -w outputs/output30 expected/expected30
	@$(VALGRIND) --log-file=outputs/memoutput31 ./pa11 inputs/extra31 outputs/output31
	diff -w outputs/output31 expected/expected31
	
clean:
	rm -f pa11 $(OBJS) outputs/*
